CREATE TABLE IF NOT EXISTS events (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    available_tickets INTEGER NOT NULL,
    category VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    date TIMESTAMP NOT NULL,
    description TEXT,
    name VARCHAR(255) NOT NULL,
    organizer_contact VARCHAR(255) NOT NULL,
    organizer_name VARCHAR(255) NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    status VARCHAR(255) NOT NULL,
    total_tickets INTEGER NOT NULL,
    venue VARCHAR(255) NOT NULL
);