# 1. Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: onlineeventbookingsohaib
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z rabbitmq 5672; do echo 'Waiting for RabbitMQ...'; sleep 2; done",
            ]
        - name: wait-for-mongodb
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z mongodb 27017; do echo 'Waiting for MongoDB...'; sleep 2; done",
            ]
      containers:
        - name: notification-service
          image: 22i1029/oebs-notification-service:latest
          envFrom:
            - secretRef:
                name: secrets
            - configMapRef:
                name: config
          env:
            - name: MONGO_USER
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: MONGO_USER
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MONGO_PASSWORD
            - name: MONGO_DB_URL
              value: mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@mongodb:27017/notificationdb?authSource=admin
            - name: RABBITMQ_URL
              value: amqp://rabbitmq
            # Or with auth:
            # RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq
            - name: USER_SERVICE_URL
              value: http://user-service:8080/users
          ports:
            - containerPort: 3001

---
# 2. Service
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: onlineeventbookingsohaib
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
